name: gomech-ai-service
services:
  - name: ai-service
    type: web
    build:
      type: docker
      dockerfile: Dockerfile
    instance_type: nano
    scaling:
      min: 1
      max: 3
    ports:
      - port: 8000
        protocol: http
    env:
      - name: ENVIRONMENT
        value: production
      - name: HOST
        value: 0.0.0.0
      - name: PORT
        value: "8000"
    health_checks:
      - path: /
        port: 8000
        initial_delay: 30
        timeout: 10
        interval: 30
